# Generated by Django 5.2.1 on 2025-05-16 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comision', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='miembrocomision',
            name='comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comision.comision'),
        ),
    ]
